module "ipam" {
    source = "../../modules/ipv6_ipam"

    vpc_ipam_description = "AWS VPC IPAM generated by brian"
    ipam_pool_description = "AWS IPAM pool description"

    tags = {
        Name = "brian-ipv6-ipam"
        Description = "ipv6 ipam for constructing dual-stack vpc"
    }
}